//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtmCashTest.WpfClient.AtmCashService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BanknoteContract", Namespace="http://schemas.datacontract.org/2004/07/AtmCashTest.WcfService.Models")]
    [System.SerializableAttribute()]
    public partial class BanknoteContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NominalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nominal {
            get {
                return this.NominalField;
            }
            set {
                if ((this.NominalField.Equals(value) != true)) {
                    this.NominalField = value;
                    this.RaisePropertyChanged("Nominal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AtmServiceFault", Namespace="http://schemas.datacontract.org/2004/07/AtmCashTest.WcfService.Models")]
    [System.SerializableAttribute()]
    public partial class AtmServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AtmCashService.IAtmCashService")]
    public interface IAtmCashService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtmCashService/PutCash", ReplyAction="http://tempuri.org/IAtmCashService/PutCashResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtmCashTest.WpfClient.AtmCashService.AtmServiceFault), Action="http://tempuri.org/IAtmCashService/PutCashAtmServiceFaultFault", Name="AtmServiceFault", Namespace="http://schemas.datacontract.org/2004/07/AtmCashTest.WcfService.Models")]
        AtmCashTest.WpfClient.AtmCashService.BanknoteContract[] PutCash(AtmCashTest.WpfClient.AtmCashService.BanknoteContract[] banknotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtmCashService/PutCash", ReplyAction="http://tempuri.org/IAtmCashService/PutCashResponse")]
        System.Threading.Tasks.Task<AtmCashTest.WpfClient.AtmCashService.BanknoteContract[]> PutCashAsync(AtmCashTest.WpfClient.AtmCashService.BanknoteContract[] banknotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtmCashService/GetCash", ReplyAction="http://tempuri.org/IAtmCashService/GetCashResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtmCashTest.WpfClient.AtmCashService.AtmServiceFault), Action="http://tempuri.org/IAtmCashService/GetCashAtmServiceFaultFault", Name="AtmServiceFault", Namespace="http://schemas.datacontract.org/2004/07/AtmCashTest.WcfService.Models")]
        AtmCashTest.WpfClient.AtmCashService.BanknoteContract[] GetCash(int sum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtmCashService/GetCash", ReplyAction="http://tempuri.org/IAtmCashService/GetCashResponse")]
        System.Threading.Tasks.Task<AtmCashTest.WpfClient.AtmCashService.BanknoteContract[]> GetCashAsync(int sum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtmCashService/GetBalance", ReplyAction="http://tempuri.org/IAtmCashService/GetBalanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtmCashTest.WpfClient.AtmCashService.AtmServiceFault), Action="http://tempuri.org/IAtmCashService/GetBalanceAtmServiceFaultFault", Name="AtmServiceFault", Namespace="http://schemas.datacontract.org/2004/07/AtmCashTest.WcfService.Models")]
        int GetBalance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtmCashService/GetBalance", ReplyAction="http://tempuri.org/IAtmCashService/GetBalanceResponse")]
        System.Threading.Tasks.Task<int> GetBalanceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAtmCashServiceChannel : AtmCashTest.WpfClient.AtmCashService.IAtmCashService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AtmCashServiceClient : System.ServiceModel.ClientBase<AtmCashTest.WpfClient.AtmCashService.IAtmCashService>, AtmCashTest.WpfClient.AtmCashService.IAtmCashService {
        
        public AtmCashServiceClient() {
        }
        
        public AtmCashServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AtmCashServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtmCashServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtmCashServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AtmCashTest.WpfClient.AtmCashService.BanknoteContract[] PutCash(AtmCashTest.WpfClient.AtmCashService.BanknoteContract[] banknotes) {
            return base.Channel.PutCash(banknotes);
        }
        
        public System.Threading.Tasks.Task<AtmCashTest.WpfClient.AtmCashService.BanknoteContract[]> PutCashAsync(AtmCashTest.WpfClient.AtmCashService.BanknoteContract[] banknotes) {
            return base.Channel.PutCashAsync(banknotes);
        }
        
        public AtmCashTest.WpfClient.AtmCashService.BanknoteContract[] GetCash(int sum) {
            return base.Channel.GetCash(sum);
        }
        
        public System.Threading.Tasks.Task<AtmCashTest.WpfClient.AtmCashService.BanknoteContract[]> GetCashAsync(int sum) {
            return base.Channel.GetCashAsync(sum);
        }
        
        public int GetBalance() {
            return base.Channel.GetBalance();
        }
        
        public System.Threading.Tasks.Task<int> GetBalanceAsync() {
            return base.Channel.GetBalanceAsync();
        }
    }
}
